<a href="https://colab.research.google.com/github/dhoneshruti59-cloud/task24/blob/main/task24_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd
import joblib

In [24]:
from google.colab import files
uploaded=files.upload()

Saving heart.csv to heart (1).csv

In [25]:
filepath="/content/heart (1).csv"
df=pd.read_csv("/content/heart (1).csv")

In [26]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [27]:
X = df.drop("HeartDisease", axis=1)
y = df["HeartDisease"]

In [28]:
X = pd.get_dummies(X, drop_first=True)

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [30]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [31]:
from sklearn.svm import SVC
best_classification_model = SVC()
best_classification_model.fit(X_train, y_train)

SVC()

In [32]:
joblib.dump(best_classification_model, "best_classification_model.pkl")
joblib.dump(scaler, "classification_scaler.pkl")
joblib.dump(columns, "classification_columns.pkl")
print("Classification Model Saved Successfully")

Classification Model Saved Successfully

In [33]:
from google.colab import files
uploaded=files.upload()

Saving ford_car_dataset.csv to ford_car_dataset.csv

In [34]:
df = pd.read_csv("/content/ford_car_dataset.csv")
df.head()

    model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0  Fiesta  2017  12000    Automatic    15944   Petrol  150  57.7         1.0
1   Focus  2018  14000       Manual     9083   Petrol  150  57.7         1.0
2   Focus  2017  13000       Manual    12456   Petrol  150  57.7         1.0
3  Fiesta  2019  17500       Manual    10460   Petrol  145  40.3         1.5
4  Fiesta  2019  16500    Automatic     1482   Petrol  145  48.7         1.0

In [35]:
X = df.drop("price", axis=1)
y = df["price"]

In [36]:
X = pd.get_dummies(X, drop_first=True)

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [38]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
num_cols = ["year", "mileage", "tax", "mpg", "engineSize"]
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

In [39]:
from sklearn.tree import DecisionTreeRegressor
best_regression_model = DecisionTreeRegressor(random_state=42)
best_regression_model.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [40]:
joblib.dump(best_regression_model, "best_regression_model.pkl")
joblib.dump(scaler, "regression_scaler.pkl")
joblib.dump(columns, "regression_columns.pkl")
print("Regression Model Saved Successfully")

Regression Model Saved Successfully

In [41]:
from google.colab import files

files.download("best_classification_model.pkl")
files.download("classification_scaler.pkl")
files.download("classification_columns.pkl")

files.download("best_regression_model.pkl")
files.download("regression_scaler.pkl")
files.download("regression_columns.pkl")