<a href="https://colab.research.google.com/github/dhoneshruti59-cloud/task24/blob/main/task24_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [4]:
from google.colab import files
uploaded=files.upload()

Saving ford_car_dataset.csv to ford_car_dataset.csv

In [5]:
filepath="/content/ford_car_dataset.csv"
df=pd.read_csv("/content/ford_car_dataset.csv")

In [6]:
df.head()

    model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0  Fiesta  2017  12000    Automatic    15944   Petrol  150  57.7         1.0
1   Focus  2018  14000       Manual     9083   Petrol  150  57.7         1.0
2   Focus  2017  13000       Manual    12456   Petrol  150  57.7         1.0
3  Fiesta  2019  17500       Manual    10460   Petrol  145  40.3         1.5
4  Fiesta  2019  16500    Automatic     1482   Petrol  145  48.7         1.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17966 entries, 0 to 17965
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         17966 non-null  object
 1   year          17966 non-null  int64
 2   price         17966 non-null  int64
 3   transmission  17966 non-null  object
 4   mileage       17966 non-null  int64
 5   fuelType      17966 non-null  object
 6   tax           17966 non-null  int64
 7   mpg           17966 non-null  float64
 8   engineSize    17966 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 1.2+ MB

In [8]:
df.isnull().sum()

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [9]:
X = df.drop("price", axis=1)
y = df["price"]

In [10]:
X=pd.get_dummies(X,drop_first=True)

In [14]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [16]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train, y_train)
y_pred=model.predict(X_test)

In [27]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
lr_mae=mean_absolute_error(y_test, y_pred)
lr_mse=mean_squared_error(y_test, y_pred)
lr_r2=r2_score(y_test, y_pred)
print("MAE :", lr_mae)
print("MSE :",lr_mse)
print("R2 Score :", lr_r2)

MAE : 1374.780819260334
MSE : 3455053.1213088655
R2 Score : 0.8458394987371056

In [19]:
from sklearn.tree import DecisionTreeRegressor
dt=DecisionTreeRegressor()
dt.fit(X_train, y_train)
y_pred_dt=dt.predict(X_test)

In [28]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
dt_mae=mean_absolute_error(y_test, y_pred_dt)
dt_mse=mean_squared_error(y_test, y_pred_dt)
dt_r2=r2_score(y_test, y_pred_dt)
print("MAE :", dt_mae)
print("MSE :", dt_mse)
print("R2 Score :", dt_r2)

MAE : 1047.848682990169
MSE : 2471167.6849146727
R2 Score : 0.8897393366655979

In [21]:
from sklearn.svm import SVR
svm=SVR()
svm.fit(X_train, y_train)
y_pred_svm=svm.predict(X_test)

In [29]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
svm_mae=mean_absolute_error(y_test, y_pred_svm)
svm_mse=mean_squared_error(y_test, y_pred_svm)
svm_r2=r2_score(y_test, y_pred_svm)
print("MAE :", svm_mae)
print("MSE :",svm_mse)
print("R2 Score :", svm_r2)

MAE : 3308.5089753384736
MSE : 19880093.468941774
R2 Score : 0.1129730667746559

In [23]:
from sklearn.neighbors import KNeighborsRegressor
nr=KNeighborsRegressor()
nr.fit(X_train, y_train)
y_pred_nr=svm.predict(X_test)

In [30]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
nr_mae=mean_absolute_error(y_test, y_pred_nr)
nr_mse=mean_squared_error(y_test, y_pred_nr)
nr_r2=r2_score(y_test, y_pred_nr)
print("MAE :",nr_mae)
print("MSE :", nr_mse)
print("R2 Score :", nr_r2)

MAE : 3308.5089753384736
MSE : 19880093.468941774
R2 Score : 0.1129730667746559

In [31]:
import pandas as pd

comparison = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Decision Tree Regressor",
        "Support Vector Regressor",
        "KNN Regressor"
    ],
    "MAE": [
        lr_mae,
        dt_mae,
        svm_mae,
        nr_mae
    ],
    "MSE": [
        lr_mse,
        dt_mse,
        svm_mse,
        nr_mse
    ],
    "R2 Score": [
        lr_r2,
        dt_r2,
        svm_r2,
        nr_r2
    ]
})

print(comparison)

                      Model          MAE           MSE  R2 Score
0         Linear Regression  1374.780819  3.455053e+06  0.845839
1   Decision Tree Regressor  1047.848683  2.471168e+06  0.889739
2  Support Vector Regressor  3308.508975  1.988009e+07  0.112973
3             KNN Regressor  3308.508975  1.988009e+07  0.112973